### ISSUE TITLE
Loop Habits import

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [daya0576/beaverhabits#1]
Hi,
Just came across this project and seems very interesting. Would be interested to import from my existing setup from the (Loop) Habits Android Project (https://github.com/iSoron/uhabits).

A sync option with the app might be a later feature as it will require collaboration from both projects but an option to move my existing habits over might be a good starting point.

**Comment by daya0576** [comment]
Hi @Gandalf-the-Blue 

Thanks for reaching out.

Good news, currently i'm actively working on the `import` feature, and it will be available in the next few weeks.

Importing from uhabit setup is a genius idea, and I will update you once it is available.
