### ISSUE TITLE
New Feature: Shared Calendar

### ISSUE THREAD

**Issue by joel72265** [daya0576/beaverhabits#11]
This app looks great.

New Feature: Shared calendar for Users and Calendar view (Month, Year view)

**Comment by daya0576** [comment]
Hi @joel72265 thanks for reaching out.

I'm not sure fully understand your feature request. Do u mean a calendar template, e.g. public holidays?

**Comment by joel72265** [comment]
that is good too but not what I was trying to suggest

Let me try to explain better, 
1) ADD a calendar which a user can use to create tasks, appointments, habits
2) make the application multi-user
3) share a calendar with specific users so all have visibility

**Comment by daya0576** [comment]
@joel72265 Sorry for the delayed response.

> ADD a calendar which a user can use to create tasks, appointments, habits

Could you provide an example of how the calendar and appointments could be incorporated into the app? It seems like this feature would require more work and might make the app more complex than a simple habit tracking tool.

> make the application multi-user
> share a calendar with specific users so all have visibility

The application is already multi-user. Do you mean that different users can share habits with each other?
Or they can simply use the same user to access the data 🤔
