### ISSUE TITLE
Updating from 3.2 to 3.3 and now my habits cannot be completed

### ISSUE THREAD

**Issue by ocean-haiyang** [daya0576/beaverhabits#19]
When I open the main page I can select any habit to be completed but upon refreshing the page the check marks return to x’s.

**Comment by ocean-haiyang** [comment]
Downgrading to 3.2 makes it work again.

**Comment by daya0576** [comment]
Thanks for reporting this issue! 

I did reproduce it locally, but it only occurs on the first load with dummy habits. 

I have fixed the issue (f0e940b) with the tag `0.3.4`. Could you help verify? Thanks :)

**Comment by ocean-haiyang** [comment]
Sadly I tried it and it did not work. Also, I was going to add a new habit to see if it worked. And it won’t let me add new habits

**Comment by ocean-haiyang** [comment]
Went back to 3.2 and the adding habits is fixed.

**Comment by ocean-haiyang** [comment]
Just for fun I tried going from 3.2 to 3.3 with total habit count set to false not true. Then went from 3.4 and the same two issues exist.

**Comment by daya0576** [comment]
Interesting, it seems like I found and resolved another defect XD 

Could you share the environment variables when you start up your Docker image? 
Since I am unable to reproduce this issue locally.

**Comment by ocean-haiyang** [comment]
Here is my current docker compose file. I have tried HABIT_COUNT true and false. Obviously, I want to use true! I tried 3.3 and 3.4 as well.

version: '3.8'

services:
  beaverhabits:
    image: daya0576/beaverhabits:0.3.2
    container_name: beaverhabits
    environment:
      FIRST_DAY_OF_WEEK: '0'
      HABITS_STORAGE: 'USER_DISK'
      MAX_USER_COUNT: '1'
      INDEX_SHOW_HABIT_COUNT: 'false'
    volumes:
      - /mnt/PATH/appdata/beaverhabits:/app/.user/
    ports:
      - '8063:8080'
    restart: unless-stopped

**Comment by daya0576** [comment]
Unfortunately, I still can not reproduce this issue from my side, could you help check the logs from docker container? For example `docker logs beaverhabits`.

**Comment by ocean-haiyang** [comment]
I am now on 3.4 and did the test. Here are my logs:

> Starting Uvicorn server in production mode...
> INFO:     Starting BeaverHabits...
> INFO:     Started server process [10]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
> INFO:     192.168.1.101:37248 - "GET / HTTP/1.1" 307 Temporary Redirect
> INFO:     [CRUD] User count query: 1
> INFO:     192.168.1.101:37248 - "GET /login HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37248 - "GET /_nicegui/2.7.0/static/nicegui.css HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37252 - "GET /_nicegui/2.7.0/static/fonts.css HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37264 - "GET /_nicegui/2.7.0/static/quasar.prod.css HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37276 - "GET /_nicegui/2.7.0/static/es-module-shims.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37282 - "GET /_nicegui/2.7.0/static/socket.io.min.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37292 - "GET /_nicegui/2.7.0/static/tailwindcss.min.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37248 - "GET /_nicegui/2.7.0/static/vue.global.prod.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37252 - "GET /_nicegui/2.7.0/static/quasar.umd.prod.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37276 - "GET /_nicegui/2.7.0/static/nicegui.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37282 - "GET /_nicegui/2.7.0/static/lang/en-US.umd.prod.js HTTP/1.1" 304 Not Modified
> INFO:     192.168.1.101:37264 - "GET /_nicegui/2.7.0/static/fonts/62873223be6b39e0.woff2 HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37264 - "GET /_nicegui/2.7.0/components/b0b17893a51343979e2090deee730538/input.js HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37264 - "GET /_nicegui/2.7.0/static/fonts/01d40c9fd448face.woff2 HTTP/1.1" 200 OK
> INFO:     ('192.168.1.101', 37294) - "WebSocket /socket.io/?client_id=e5c845c1-6e49-4fd1-9cbe-4266b2f8c311&EIO=4&transport=websocket" [accepted]
> INFO:     connection open
> INFO:     192.168.1.101:37264 - "GET /_nicegui/2.7.0/static/fonts/e62204447c1ed92a.woff2 HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37248 - "GET /_nicegui/2.7.0/static/fonts/0c19a63c7528cc1a.woff2 HTTP/1.1" 200 OK
> INFO:     connection closed
> INFO:     Getting user timezone...
> INFO:     Getting user habit list
> INFO:     Rendering page: /
> INFO:     192.168.1.101:37300 - "GET / HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37300 - "GET /_nicegui/2.7.0/components/b0b17893a51343979e2090deee730538/link.js HTTP/1.1" 200 OK
> INFO:     192.168.1.101:37308 - "GET /_nicegui/2.7.0/components/ef7d009c7e812da10f8aa235954c0e12/refreshable.js HTTP/1.1" 200 OK
> INFO:     ('192.168.1.101', 37310) - "WebSocket /socket.io/?client_id=26038140-793b-4910-bd99-505fc20c83a6&EIO=4&transport=websocket" [accepted]
> INFO:     connection open
> INFO:     User timezone from browser: America/New_York
> INFO:     Day 2024-12-02 ticked: True
> ERROR:nicegui:[Errno 13] Permission denied: '.user/email@pm.me.json'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
>     task.result()
>   File "/usr/local/lib/python3.12/site-packages/nicegui/storage.py", line 71, in backup
>     async with aiofiles.open(self.filepath, 'w', encoding=self.encoding) as f:
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/base.py", line 63, in __aenter__
>     return await self
>            ^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/base.py", line 59, in __await__
>     self._obj = yield from self._coro.__await__()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open
>     f = await loop.run_in_executor(executor, cb)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> PermissionError: [Errno 13] Permission denied: '.user/email@pm.me.json'
> INFO:     Day 2024-12-02 ticked: True
> ERROR:nicegui:[Errno 13] Permission denied: '.user/email@pm.me.json'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
>     task.result()
>   File "/usr/local/lib/python3.12/site-packages/nicegui/storage.py", line 71, in backup
>     async with aiofiles.open(self.filepath, 'w', encoding=self.encoding) as f:
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/base.py", line 63, in __aenter__
>     return await self
>            ^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/base.py", line 59, in __await__
>     self._obj = yield from self._coro.__await__()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open
>     f = await loop.run_in_executor(executor, cb)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> PermissionError: [Errno 13] Permission denied: '.user/email@pm.me.json'
> INFO:     connection closed
> INFO:     Getting user timezone...
> INFO:     User timezone from storage: America/New_York
> INFO:     Getting user habit list
> INFO:     Rendering page: /
> INFO:     192.168.1.101:49192 - "GET / HTTP/1.1" 200 OK
> INFO:     ('192.168.1.101', 49208) - "WebSocket /socket.io/?client_id=fc638890-a1a8-4895-b6cd-521fa767d2f3&EIO=4&transport=websocket" [accepted]
> INFO:     connection open

**Comment by ocean-haiyang** [comment]
Just turned on habit_count and still no issues! Sorry if I caused you extra work. Glad it's solved :)

**Comment by daya0576** [comment]
No worries, that's great to hear the issue has been resolved!  Please feel free to report any future issues :)
