### ISSUE TITLE
Everyone can sign up

### ISSUE THREAD

**Issue by MonsteraCompany** [daya0576/beaverhabits#2]
Can you add a variable to avoid anyone to sign up?

**Comment by daya0576** [comment]
Thank you for your suggestion. 

Since at least one user needs to be created first to use this application.  Instead of implementing admin account system, I am going to add a simple global variable called `MAX_USER_COUNT`. By setting it to `1`, you can prevent others from signing up in the future.

Does it sound good to you?

**Comment by MonsteraCompany** [comment]
Sounds

> Thank you for your suggestion.
> 
> Since at least one user needs to be created first to use this application. Instead of implementing admin account system, I am going to add a simple global variable called `MAX_USER_COUNT`. By setting it to `1`, you can prevent others from signing up in the future.
> 
> Does it sound good to you?



> Thank you for your suggestion.
> 
> Since at least one user needs to be created first to use this application. Instead of implementing admin account system, I am going to add a simple global variable called `MAX_USER_COUNT`. By setting it to `1`, you can prevent others from signing up in the future.
> 
> Does it sound good to you?

Sounds great to me! Thanks

**Comment by daya0576** [comment]
Hi @MonsteraCompany and @astingengo, apologize for the long wait. Please use the latest image to utilize the `MAX_USER_COUNT` parameter to limit sign up. 

If the user count reaches the threshold, the sign-up link will disappear. If someone tries to visit the page using a specific path, a 404 error will be returned.
<img width="500" alt="image" src="https://github.com/user-attachments/assets/4dbc55f3-f104-44c1-9326-5137f376b219">

Please check readme page for more details.
