### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by nov1n** [daya0576/beaverhabits#25]
Hi, thank you for building this!

I'm looking to build a [StreamDeck](https://www.elgato.com/ww/en/p/stream-deck-mk2-black) client for your app. The grid would be perfect to display habit progress, similar to the current UI. Clicking buttons would toggle the habit completion, and I thought about using colors or icons to display the state of a habit.

I'm not familiar with the nicegui framework you used, but after skimming the code it looks like the frontend and the backend code are woven together.

It would be nice to have a [Swagger UI](https://swagger.io/tools/swagger-ui/) or a request collection for Postman/Insomnia to document the endpoints. Is this something that you would be willing to add?

**Comment by daya0576** [comment]
Hi @nov1n thanks for reaching out. I was just considering offering RESTful APIs just an hour ago :) 

Just to confirm, are you looking for something like this: 
```shell
GET /api/v1/habits               # Retrieve all habits
GET /api/v1/habits/{id}          # Retrieve a specific habit by id
POST /api/v1/habits              # Create a new habit
PUT /api/v1/habits/{id}          # Update a habit by id
DELETE /api/v1/habits/{id}       # Delete a habit by id

POST /api/v1/habits/{id}/tick    # Update a habit by id
```

**Comment by nov1n** [comment]
Yes, exactly like that. 👍

If you don't want to send the entire list of 'completions' every time it could be nice to add some query parameters like `limit=5&sort=asc&date_start=18-12-2024&date_end=20-12-2024` to retrieve the 5 most recent completions between the 18th and the 20th of December.

That said, it might not be a problem, since the data structure for each completion is small, so this sort of filtering can also be done by the client.

**Comment by daya0576** [comment]
Got it, the project is based on the fastapi framework with native Swagger UI support, so it won't require much effort to add these APIs and docs. I will inform you as soon as the APIs are available 💪

**Comment by daya0576** [comment]
Hi @nov1n, the Swagger UI API documentation is available now: https://beaverhabits.com/docs#/habits

I have drafted a wiki outlining the basic workflow: [Beaver Habit Tracker API How‐to Guide](https://github.com/daya0576/beaverhabits/wiki/Beaver-Habit-Tracker-API-How%E2%80%90to-Guide), e.g. list and complete habit. It also includes a nice postman collection :) 

However, not all of the APIs have been implemented yet. Feel free to ask any further questions.

**Comment by nov1n** [comment]
This looks great! I'll have some time to look at this in the next weeks and I'll share any feedback. Thanks again.

**Comment by nov1n** [comment]
The APIs you provided worked perfectly. The current version shows the past 5 days of 3 habits of your choice. Clicking on a checkbox will toggle it and sync it with BeaverHabits. The state also refreshes every 30 seconds in case habits were modified through other means.

I'll try it out for a week and if I like it I'll post the code as a [Spoon](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md) for others to use.

Thanks again!

https://github.com/user-attachments/assets/7b7e157d-c909-4c60-8bee-1edc11605244

**Comment by nov1n** [comment]
I uploaded the code here: https://github.com/nov1n/HabitDeck, feel free to mention it in your README. The issue can be closed 🎉.

**Comment by daya0576** [comment]
@nov1n Thanks, the demo looks sososo sexy! I have updated the project to [readme](https://github.com/daya0576/beaverhabits?tab=readme-ov-file#derivatives), let me know if you have any further questions.
