### ISSUE TITLE
Change the add section to edit

### ISSUE THREAD

**Issue by ocean-haiyang** [daya0576/beaverhabits#27]
Since it is really the add and delete section

**Comment by daya0576** [comment]
Thanks for reaching out, sorry I didnt get it. Would you like me to provide a screenshot or can you explain the suggestion further? 😃

**Comment by ocean-haiyang** [comment]
I am suggesting you change the name of the add button to edit because you can edit, add, and delete all in the add tab

**Comment by daya0576** [comment]
😁 I personally prefer the current naming convention. 

Perhaps, in the future, I will offer an option to customize the name mapping for the menu.

**Comment by junelac** [comment]
Just to say that I was also confused by the name Add, I was thinking it was just to add habits and not edit them. Maybe some message the first time it is open would help ?
