### ISSUE TITLE
Add edit including delete in the individual habits page

### ISSUE THREAD

**Issue by ocean-haiyang** [daya0576/beaverhabits#28]
Would make sense to edit when looking at the expanded view

**Comment by daya0576** [comment]
Thanks for reaching out. Are you suggesting adding an edit button on each individual habit page?
<img width="413" alt="image" src="https://github.com/user-attachments/assets/8b94777c-dd5c-4b28-84e5-92e9a46f70ef">

**Comment by ocean-haiyang** [comment]
Yes that would be great!

**Comment by daya0576** [comment]
I see, but currently there is no edit page for an individual habit. 🤔

**Comment by ocean-haiyang** [comment]
Closing because it seems unplanned.
