### ISSUE TITLE
Add the option to hide a habit

### ISSUE THREAD

**Issue by ocean-haiyang** [daya0576/beaverhabits#29]
This way one can pause a habit without deleting its history

**Comment by daya0576** [comment]
Glad to share that this function is already available. 

There are several states of habits:
- Normal
- Archieved
- Deleted

As long as the habit is "deleted" in the `add` page, the habit is actually achieved and you can easily restore or permanently delete it from the `order` page.

**Comment by ocean-haiyang** [comment]
Where is the order page?

**Comment by daya0576** [comment]
You can access the order page either by path `/gui/order`, or the button in the add page (newly added entry from `v0.3.5`)
<img width="432" alt="image" src="https://github.com/user-attachments/assets/74be2904-3640-4fab-8100-bbefd6694582">

**Comment by ocean-haiyang** [comment]
I see it. Works well! Maybe a little unintuitive but works well

**Comment by ocean-haiyang** [comment]
I see it. Maybe a little unintuitive but works well
