### ISSUE TITLE
Cannot order them

### ISSUE THREAD

**Issue by astingengo** [daya0576/beaverhabits#3]
I would like to have this feature implemented to be able to order them later

**Comment by daya0576** [comment]
Thank you for reaching out. 

I have a similar need to organize habit lists, but I implemented it by using stars to prioritize habits:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/9aa2153e-64a7-461f-a3ed-44e8caee5ed4">

**Comment by astingengo** [comment]
Yes I saw that but that option will just push the to top ... I want to order them like drag them on the position I would like to see in the list

Thank you for your great work here

**Comment by daya0576** [comment]
I see, will figure out a workaround to order them.

**Comment by daya0576** [comment]
Hi @astingengo, a "secret" page was created to order habits: `/gui/order` :")

**Comment by daya0576** [comment]
Please check `v0.3.0` for this new feature, you can simply drag any habit to reorder it.

BTW, it's still an experimental feature. I will refine the page and integrate it into the main workflow in the future.
<img width="399" alt="image" src="https://github.com/user-attachments/assets/5819b573-b836-4337-8d3e-bdac03d54b74">

**Comment by daya0576** [comment]
Hi, this feature has been released and is now available through the menu. Please don't hesitate to reply if you have any other questions.
