### ISSUE TITLE
beaverhabit creates for every health check request a new storage-user-ID.json

### ISSUE THREAD

**Issue by RogerSik** [daya0576/beaverhabits#45]
beaverhabit creates for every health check request a new storage-user-ID.json

```
I have no name!@beaverhabits-547ccd8b7c-sp6v5:/app/.user/.nicegui$ date && ls -1 | wc -l
Mon Dec 23 14:22:16 UTC 2024
20035
I have no name!@beaverhabits-547ccd8b7c-sp6v5:/app/.user/.nicegui$

I have no name!@beaverhabits-547ccd8b7c-sp6v5:/app/.user/.nicegui$ date && ls -1 | wc -l
Mon Dec 23 14:22:36 UTC 2024
20039
I have no name!@beaverhabits-547ccd8b7c-sp6v5:/app/.user/.nicegui$
```
Content of file
```
$ cat /app/.user/.nicegui/storage-user-ffffb4c9-5c95-4310-be57-ed5300ebae8e.json
{"referrer_path":"/"}
```

currently workaround. Deleting /app/.user/.nicegui/* because im using the sqlite db.

**Comment by daya0576** [comment]
Hi @RogerSik thanks for reaching out. 

Each `storage-user-ID.json` file represents one session and should be reused until the session expires.

I am unable to reproduce this issue locally. Could you please double-check your browser's cookie settings? Thank you.

**Comment by daya0576** [comment]
Could you please provide the version you are using? I will double-check this issue.

**Comment by RogerSik** [comment]
Sure. I use the image daya0576/beaverhabits:0.4

**Comment by RogerSik** [comment]
The health check is generated every minute by Kubernetes. So It cant be only my browser. I sent later my entire setup.

**Comment by RogerSik** [comment]
image: daya0576/beaverhabits:0.4 

env variables:
```
MAX_USER_COUNT: '1'
```

Health Chech:
```
httpGet:
  path: /
  port: 8080
```

**Comment by daya0576** [comment]
I see, Kubernetes visits the health page (without a cookie), and the web app treats it as a completely new request.

Could you try changing the health page path from `/` to `/health`?

**Comment by RogerSik** [comment]
Yes that helped. Many thanks @daya0576 :)
