### ISSUE TITLE
Adding, editing, removing Habits?

### ISSUE THREAD

**Issue by deanbirnie** [daya0576/beaverhabits#47]
Have I done something wrong or am I just unable to add, delete or edit through the UI? Even your API documentation is incomplete, you make mention of API routes to perform some of these actions but no further details. API docs only include basic GET requests for info.

**Comment by deanbirnie** [comment]
Closing because I found the issue why the page wasn't loading. Have also added to my postman collection.

**Comment by livehybrid** [comment]
How did you fix this @deanbirnie ? Im having the same issue. Thanks

**Comment by ocean-haiyang** [comment]
> How did you fix this @deanbirnie ? Im having the same issue. Thanks

You can edit habits in the add page. The maintainer prefers that naming for some reason

**Comment by livehybrid** [comment]
Thanks @ocean-haiyang - I was on the edge of deleting the install, Thanks :)

**Comment by ocean-haiyang** [comment]
glad I could help! :)
