### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nov1n** [daya0576/beaverhabits#48]
https://github.com/user-attachments/assets/19bb8922-9cc8-4c43-8a2f-ab946027f1e0

It appears that there is a potential memory leak issue when calling the `/api/v1/habits/<id>` endpoint, and possibly other endpoints as well. The memory usage, as shown in the top pane displaying the output of the `docker stats beaverhabits` command, shows a monotonic increase. For this reproduction, I executed 5 requests per second in the bottom pane. The memory leak issue became severe enough that it caused my server to crash due to running out of memory yesterday.

**Comment by daya0576** [comment]
Thanks for reporting this issue. 

There's nothing that excites SREs more than a memory leak :p 

Definitely will look into it in the next few days.

**Comment by daya0576** [comment]
@nov1n The memory leak issue has been fixed by PR #49 💪

And the latest docker image was also published with the tag `0.4.1` 


Please give it a try and feel free to report if the issue still persists.

**Comment by nov1n** [comment]
I had a chance to try the new version and the issue looks fixed. Thanks for the quick turnaround and happy holidays! 🧑🏼‍🎄
