### ISSUE TITLE
center the page so it works on desktop web as well

### ISSUE THREAD

**Issue by ocean-haiyang** [daya0576/beaverhabits#9]
it is currently set to move left instead of center making desktop web use awkward.

**Comment by daya0576** [comment]
Hi @ocean-haiyang, thank you for reaching out.

Actually, it's by design, but I will create a variable to customize this behaviour, is it ok for you?

**Comment by ocean-haiyang** [comment]
> Hi @ocean-haiyang, thank you for reaching out.
> 
> Actually, it's by design, but I will create a variable to customize this behaviour, is it ok for you?

Making it center and larger for desktop would be amazing! :)

I suck at coding but I found this centered it in the layout.py

`def layout(title: str | None = None, with_menu: bool = True):
    """Base layout for all pages."""
    root_path = get_root_path()
    title = title or get_page_title(root_path)
    with ui.column().classes("max-w-lg mx-auto"):`

IDK how to request a pull

**Comment by ocean-haiyang** [comment]
Hey, can you consider adding the function that I commented? @daya0576 It doesn't mess with the mobile experience at all.

**Comment by daya0576** [comment]
@ocean-haiyang Apologize for the delayed response. To ensure the current behavior is not changed, I have introduced a new variable called `ENABLE_DESKTOP_ALGIN_CENTER` to manage this feature. 

If the test passed. I will release the latest version of the docker image in the next few days.

**Comment by ocean-haiyang** [comment]
Cannot wait! Love your simple but great application so far :)

**Comment by daya0576** [comment]
Hi @ocean-haiyang, I have set this behavior as the default. Please check the latest docker image or [demo page](https://beaverhabits.com/demo).
